<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test Case Started : Login_Data]]>
    </line>
    <line>
      <![CDATA[Test Case Success : 1]]>
    </line>
    <line>
      <![CDATA[Test Case Started : Add_Group]]>
    </line>
    <line>
      <![CDATA[Test Case Failure : 2]]>
    </line>
    <line>
      <![CDATA[Test Case Started : Add_Role]]>
    </line>
    <line>
      <![CDATA[Test Case Failure : 2]]>
    </line>
    <line>
      <![CDATA[Test Case Started : Add_User]]>
    </line>
    <line>
      <![CDATA[Test Case Success : 1]]>
    </line>
  </reporter-output>
  <suite started-at="2025-09-22T16:19:42 IST" name="Suite" finished-at="2025-09-22T16:19:54 IST" duration-ms="11661">
    <groups>
    </groups>
    <test started-at="2025-09-22T16:19:42 IST" name="Test" finished-at="2025-09-22T16:19:54 IST" duration-ms="11661">
      <class name="test_case.Login">
        <test-method is-config="true" signature="Launch_Browser()[pri:0, instance:test_case.Login@55795845]" started-at="2025-09-22T16:19:42 IST" name="Launch_Browser" finished-at="2025-09-22T16:19:46 IST" duration-ms="3534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch_Browser -->
        <test-method signature="Login_Data(java.lang.String,java.lang.String)[pri:0, instance:test_case.Login@55795845]" started-at="2025-09-22T16:19:47 IST" name="Login_Data" data-provider="LoginCredentials" finished-at="2025-09-22T16:19:48 IST" duration-ms="989" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Approver]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[User@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test Case Started : Login_Data]]>
            </line>
            <line>
              <![CDATA[Test Case Success : 1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login_Data -->
      </class> <!-- test_case.Login -->
      <class name="test_case.Access_permissions">
        <test-method is-config="true" signature="Access_Permissions_Setup()[pri:0, instance:test_case.Access_permissions@165b8a71]" started-at="2025-09-22T16:19:48 IST" name="Access_Permissions_Setup" finished-at="2025-09-22T16:19:48 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Access_Permissions_Setup -->
        <test-method signature="Add_Group()[pri:1, instance:test_case.Access_permissions@165b8a71]" started-at="2025-09-22T16:19:48 IST" name="Add_Group" finished-at="2025-09-22T16:19:49 IST" duration-ms="1506" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Submit is clicked : Not Clicked]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Submit is clicked : Not Clicked
at utilities.Helper_Class.safeClick(Helper_Class.java:35)
at Page_Objects.Access_Permissions_page.addgroup(Access_Permissions_page.java:164)
at test_case.Access_permissions.Add_Group(Access_permissions.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[Test Case Started : Add_Group]]>
            </line>
            <line>
              <![CDATA[Test Case Failure : 2]]>
            </line>
          </reporter-output>
        </test-method> <!-- Add_Group -->
        <test-method signature="Add_Role()[pri:2, instance:test_case.Access_permissions@165b8a71]" started-at="2025-09-22T16:19:49 IST" name="Add_Role" finished-at="2025-09-22T16:19:50 IST" duration-ms="843" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Add New Role : Not Clicked]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Add New Role : Not Clicked
at utilities.Helper_Class.safeClick(Helper_Class.java:35)
at Page_Objects.Access_Permissions_page.addrole(Access_Permissions_page.java:175)
at test_case.Access_permissions.Add_Role(Access_permissions.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[Test Case Started : Add_Role]]>
            </line>
            <line>
              <![CDATA[Test Case Failure : 2]]>
            </line>
          </reporter-output>
        </test-method> <!-- Add_Role -->
        <test-method signature="Add_User()[pri:3, instance:test_case.Access_permissions@165b8a71]" started-at="2025-09-22T16:19:50 IST" name="Add_User" finished-at="2025-09-22T16:19:54 IST" duration-ms="3565" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Test Case Started : Add_User]]>
            </line>
            <line>
              <![CDATA[Test Case Success : 1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Add_User -->
      </class> <!-- test_case.Access_permissions -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
